### ISSUE TITLE
On sliderblock init loading never ends

### ISSUE THREAD

**Issue by busykoala** [4teamwork/ftw.sliderblock#41]
The behaviour is described in https://github.com/4teamwork/demo.web/pull/81

When pressed upload on block creation `else` is called in https://github.com/4teamwork/ftw.sliderblock/blob/4df6a8c0d9825d058995ce8fd817b94af4da9ef8/ftw/sliderblock/browser/resources/sliderblock.js#L37-L41

It can, but probably should not be solved by deleting the lines mentioned (else part of condition).

**Comment by maethu** [comment]
Thanks, I'll fix it asap.
