### ISSUE TITLE
Fix dependency issue.

### ISSUE THREAD

**Issue by busykoala** [4teamwork/ftw.sliderblock#45]
In https://github.com/4teamwork/ftw.sliderblock/blob/a5f6b509d6743d9f6c713083ff193d63be0061b1/ftw/sliderblock/browser/configure.zcml#L20 an interface is provided which is not a dependency.

I noticed when I updated ftw.simplelayout from `1.23.11` to `2.4.1` but ftw.sliderblock was still on version 1.5.0.
Since `collective.quickupload` was removed as a dependency in `ftw.simplelayout 2.2.0` it is missing now. https://github.com/4teamwork/ftw.simplelayout/blob/f0b4d01be338b90275d83a8ef6fa55cbc2868936/docs/HISTORY.txt#L36-L44

**Comment by maethu** [comment]
Invest max 2h
